### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by majosalazar** [majosalazar/scl-2018-05-bc-core-am-datadashboard#4]
Herramientas que debemos manejar

- [x] Array en MDN
- [x] Array.sort en MDN
- [x] Array.map  en MDN
- [x] Array.filter  en MDN
- [x] Array.reduce en MDN
- [x] Array.forEach en MDN
- [x] Object.keys  en MDN
- [x] Object.entries en MDN
- [x] XMLHttpRequest en MDN
- [x] Fetch API en MDN
- [ ] json.org # #

**Comment by majosalazar** [comment]
HTML

**Comment by majosalazar** [comment]
CSS

**Comment by majosalazar** [comment]
DOM

**Comment by Marielk** [comment]
entrando al planning

**Comment by Marielk** [comment]
-Interfaz de usuario (maximo terminar hoy) 
-Funcionalidad (hasta el jueves temprano)
-pasos finales (maximo viernes muuuuy temprano antes de las 10 am)

**Comment by Marielk** [comment]
//rutas de archivos json
cohorts: require('../data/cohorts.json'),
  progress: require('../data/cohorts/lim-2018-03-pre-core-pw/progress.json'),
  users: require('../data/cohorts/lim-2018-03-pre-core-pw/users.json'),

//Debe haber una funcion global, dentro deben estar las siguientes funciones 
### **>función computeUsersStats**
//deberia obtener la sig info 
(users, progress, courses)
//'debería retornar arreglo de usuarios con propiedad stats'
//deberia ser un arreglo 
(user.hasOwnProperty('stats')
//deberia contener los sig objetos
isNumber(user.stats.percent);
isObject(user.stats.exercises);
isObject(user.stats.quizzes);
isObject(user.stats.reads);

//deber coincidir con validaciones que aparecen con alumna de prueba en linea 39

### **>función sortUsers**
//deberia obtener la sig info 
users, orderBy, orderDirection
//deberia ordenar los datos de la siguiente manera: 
it('debería retornar arreglo de usuarios ordenado por nombre ASC');
it('debería retornar arreglo de usuarios ordenado por nombre DESC');
it('debería retornar arreglo de usuarios ordenado por porcentaje general ASC');
it('debería retornar arreglo de usuarios ordenado por porcentaje general DESC');
it('debería retornar arreglo de usuarios ordenado por ejercicios completados ASC');
it('debería retornar arreglo de usuarios ordenado por ejercicios completados DESC');
it('debería retornar arreglo de usuarios ordenado por quizzes completados ASC');
it('debería retornar arreglo de usuarios ordenado por quizzes completados DESC');
it('debería retornar arreglo de usuarios ordenado por score promedio en quizzes completados ASC');
it('debería retornar arreglo de usuarios ordenado por score promedio en quizzes completados DESC');
it('debería retornar arreglo de usuarios ordenado por lecturas (reads) completadas ASC');
it('debería retornar arreglo de usuarios ordenado por lecturas (reads) completadas DESC');

### **>función filterUsers**
//deberia obtener la sig info 
(users, filterBy)
//'debería retornar nuevo arreglo solo con usuarios con nombres que contengan string (case insensitive)'

### **>función processCohortData**
//deberia obtener la sig info 
({ cohortData, orderBy, orderDirection, filterBy })
//'debería retornar arreglo de usuarios con propiedad stats y aplicar sort y filter'
